apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: canister
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
